/* My Little Money Home v5 — mobile-first, local-first, mixed-media Y2K scrapbook. */
const DAY=86400000;
const PAY_FREQ={weekly:52,biweekly:26,semimonthly:24,monthly:12};
const CATEGORIES=["Things for Me","Experiences","Home","Gifts","Giving & Causes","Hobby / Creative","Beauty","Travel","Other"];
const CLOTHES=["Tops","Bottoms","Dresses","Shoes","Bags","Outerwear","Accessories","Other"];
const ICONS={"Things for Me":"🎀","Experiences":"🎟️","Home":"🏡","Gifts":"🎁","Giving & Causes":"💞","Hobby / Creative":"🎨","Beauty":"🫧","Travel":"✈️","Other":"⭐"};
const GAME_MODES={classic:"CLASSIC",boost:"LITTLE BOOST",neglected:"NEGLECTED WISH",giving:"GIVING DAY",treat:"TREAT DAY",steady:"SLOW + STEADY"};
const BUILTIN_ACTIVITIES=[
  "go to the park","walk outside with a favorite playlist","go to the library","write for twenty minutes","paint something tiny","play a record front to back","burn incense and tidy one corner","light a candle and read","take care of your plants","have a jam session and clean","play dress up with clothes you own","make a pile of clothes to sell","eat fruit somewhere sunny","make a vegetable snack","walk a trail or walking path","climb at a free/public spot if available","take photos of interesting textures","make a collage from old magazines","rearrange a shelf","learn one dance from a video","call a friend and walk together","watch the sunset","visit a free museum day","draw your dream room","make a playlist for a future trip","do a no-spend picnic with food you already have","style three outfits from your closet","write postcards you already own","make tea and sit outside","practice a hobby you forgot you had"
];
const WHO=["solo date","with a friend","with family","invite someone you miss","just you + your headphones"];
const WHERE=["outside","at home","at a park","at the library","somewhere you can walk","on the floor with a blanket","by a window","in your neighborhood"];
const WHEN=["after work","this morning","this afternoon","tonight","this weekend","when you feel like shopping","the next free hour"];

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,8)+Date.now().toString(36);
const num=v=>Number(v||0), clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const todayISO=()=>new Date().toISOString().slice(0,10);
const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(num(v));
const fmtDate=d=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"—";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const attr=s=>esc(s).replace(/`/g,"&#096;");
const deep=o=>JSON.parse(JSON.stringify(o));
const daysAgo=d=>Math.max(0,Math.floor((Date.now()-new Date(`${d}T12:00:00`).getTime())/DAY));
const addDays=(d,n)=>{const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+num(n));return x.toISOString().slice(0,10)};
const diffDays=(a,b)=>Math.ceil((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/DAY);
const monthKey=d=>String(d||todayISO()).slice(0,7);

const DEFAULT_STATE={
  version:5,
  settings:{payFrequency:"biweekly",savePct:30,funPct:20,defaultWaitDays:30,sound:false,sparkle:true,coolLow:2,coolMid:5,coolHigh:10,coolLuxury:21,roomBackgrounds:{},roomPatterns:{}},
  paychecks:[],costs:[],sinkingFunds:[],savingsGoals:[],savingsContribs:[],sinkingContribs:[],
  wishes:[],rolls:[],impulses:[],memories:[],
  notebooks:[{id:"starterbook",title:"my little rules",body:"",color:"pink"}],
  owned:[],outfits:[],bags:[],adventures:[],customActivities:[],
  game:{mode:"classic",lastWishId:null,session:"tiny roll"}
};

function migrateV4(v){
  const s=deep(DEFAULT_STATE); if(!v)return s;
  s.settings={...s.settings,...(v.settings||{}),roomBackgrounds:{}};
  ["paychecks","costs","sinkingFunds","savingsGoals","savingsContribs","sinkingContribs","wishes","rolls","impulses","memories"].forEach(k=>s[k]=Array.isArray(v[k])?v[k]:[]);
  s.notebooks=(v.notes||[]).length?(v.notes||[]).map(n=>({id:n.id||uid(),title:n.title||"note",body:n.body||n.text||"",color:n.color||"yellow"})):s.notebooks;
  s.game={...s.game,...(v.game||{})};
  s.version=5; return normalize(s);
}
function normalize(s){
  const b=deep(DEFAULT_STATE);s={...b,...(s||{}),settings:{...b.settings,...(s?.settings||{}),roomBackgrounds:{...(s?.settings?.roomBackgrounds||{})}},game:{...b.game,...(s?.game||{})}};
  ["paychecks","costs","sinkingFunds","savingsGoals","savingsContribs","sinkingContribs","wishes","rolls","impulses","memories","notebooks","owned","outfits","bags","adventures","customActivities"].forEach(k=>{if(!Array.isArray(s[k]))s[k]=[]});
  s.wishes=s.wishes.map(w=>({...w,id:w.id||uid(),price:num(w.price),baseSaved:num(w.baseSaved??w.saved),waitDays:num(w.waitDays||30),status:w.status||"waiting",mediaKey:w.mediaKey||""}));
  s.savingsGoals=s.savingsGoals.map(g=>({...g,id:g.id||uid(),target:num(g.target),baseSaved:num(g.baseSaved??g.saved),mediaKey:g.mediaKey||"",type:g.type||"Long Term"}));
  s.owned=s.owned.map(o=>({...o,id:o.id||uid(),mediaKey:o.mediaKey||""}));
  return s;
}
function loadState(){
  try{const v5=localStorage.getItem("littleMoneyHomeV5");if(v5)return normalize(JSON.parse(v5));const v4=localStorage.getItem("littleMoneyHomeV4");if(v4){const x=migrateV4(JSON.parse(v4));localStorage.setItem("littleMoneyHomeV5",JSON.stringify(x));return x}}
  catch(e){console.warn(e)} return deep(DEFAULT_STATE)
}
function saveState(){try{localStorage.setItem("littleMoneyHomeV5",JSON.stringify(state))}catch(e){toast("storage is full — export a backup ♡")}}
let state=loadState(),route="home",currentRoll=null,selectedOutfit=new Set(),selectedBag=new Set(),activeNotebook=state.notebooks[0]?.id||null,adventureRoll=null;

/* ---------- IndexedDB media ---------- */
const Media={
  db:null,urls:new Map(),
  async open(){if(this.db)return this.db;this.db=await new Promise((res,rej)=>{const q=indexedDB.open("moneyhomeMediaV1",1);q.onupgradeneeded=()=>q.result.createObjectStore("media");q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});return this.db},
  async put(blob,key=uid()){const db=await this.open();await new Promise((res,rej)=>{const tx=db.transaction("media","readwrite");tx.objectStore("media").put(blob,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});return key},
  async get(key){if(!key)return null;const db=await this.open();return await new Promise((res,rej)=>{const q=db.transaction("media").objectStore("media").get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})},
  async url(key){if(!key)return "";if(this.urls.has(key))return this.urls.get(key);const b=await this.get(key);if(!b)return "";const u=URL.createObjectURL(b);this.urls.set(key,u);return u},
  async del(key){if(!key)return;const db=await this.open();await new Promise((res,rej)=>{const tx=db.transaction("media","readwrite");tx.objectStore("media").delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});if(this.urls.has(key)){URL.revokeObjectURL(this.urls.get(key));this.urls.delete(key)}},
  async keys(){const db=await this.open();return await new Promise((res,rej)=>{const q=db.transaction("media").objectStore("media").getAllKeys();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
};
async function shrinkImage(file){
  if(file.type==="image/gif")return file;
  try{const bmp=await createImageBitmap(file);const max=1400,scale=Math.min(1,max/Math.max(bmp.width,bmp.height));const c=document.createElement("canvas");c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext("2d").drawImage(bmp,0,0,c.width,c.height);return await new Promise(r=>c.toBlob(b=>r(b||file),"image/webp",.84))}catch(e){return file}
}
async function saveUpload(file,oldKey=""){if(!file)return oldKey;const blob=await shrinkImage(file);const key=await Media.put(blob);if(oldKey&&oldKey!==key)await Media.del(oldKey);return key}
async function hydrateMedia(root=document){
  const nodes=$$("[data-media]",root);await Promise.all(nodes.map(async n=>{const u=await Media.url(n.dataset.media);if(!u)return;if(n.tagName==="IMG")n.src=u;else n.style.backgroundImage=`url(${u})`}));
  const bg=state.settings.roomBackgrounds[ROUTE_ROOM[route]||route];if(bg){const u=await Media.url(bg);$("#roomBackdrop").style.backgroundImage=u?`url(${u})`:""}else $("#roomBackdrop").style.backgroundImage="";
}
function mediaImg(key,cls="",alt=""){return key?`<img class="${cls}" data-media="${key}" alt="${attr(alt)}">`:""}

/* ---------- money logic ---------- */
function annualCost(c){const a=num(c.amount);return c.frequency==="weekly"?a*52:c.frequency==="quarterly"?a*4:c.frequency==="annual"?a:a*12}
function protectedPerPay(){return state.costs.reduce((t,c)=>t+annualCost(c),0)/(PAY_FREQ[state.settings.payFrequency]||26)}
function sinkingCurrent(f){return num(f.baseSaved)+state.sinkingContribs.filter(c=>c.fundId===f.id).reduce((a,c)=>a+num(c.amount),0)}
function goalCurrent(g){return num(g.baseSaved)+state.savingsContribs.filter(c=>c.goalId===g.id).reduce((a,c)=>a+num(c.amount),0)}
function sinkingRecommendation(f){if(!f.dueDate)return 0;const rem=Math.max(0,num(f.target)-sinkingCurrent(f));if(!rem)return 0;const days=Math.max(1,diffDays(todayISO(),f.dueDate));const pays=Math.max(1,Math.ceil(days/365*(PAY_FREQ[state.settings.payFrequency]||26)));return rem/pays}
function planIncome(amount){amount=num(amount);const protectedAmt=protectedPerPay(),sinking=state.sinkingFunds.reduce((t,f)=>t+sinkingRecommendation(f),0),left=Math.max(0,amount-protectedAmt-sinking),save=left*state.settings.savePct/100,fun=left*state.settings.funPct/100,free=Math.max(0,left-save-fun);return {protected:protectedAmt,sinking,leftover:left,savings:save,fun,free}}
function latestPay(){return [...state.paychecks].sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0]||null}
function wishSaved(w){return num(w.baseSaved)+state.rolls.filter(r=>r.wishId===w.id).reduce((a,r)=>a+num(r.amount),0)}
function funIn(){return state.paychecks.reduce((a,p)=>a+num(p.snapshot?.fun),0)}
function impulseOut(){return state.impulses.filter(x=>x.deductFun&&!x.returned).reduce((a,x)=>a+num(x.amount),0)}
function funJar(){return funIn()-state.rolls.reduce((a,r)=>a+num(r.amount),0)-impulseOut()}
function progressVal(saved,target){return target?clamp(Math.round(num(saved)/num(target)*100),0,100):0}
function coolDays(price){price=num(price);return price>=1000?state.settings.coolLuxury:price>=300?state.settings.coolHigh:price>=100?state.settings.coolMid:state.settings.coolLow}
function syncWishes(){state.wishes.forEach(w=>{const sv=wishSaved(w);if(w.status==="active"&&sv>=w.price){w.status="ready";w.fundedDate=w.fundedDate||todayISO();w.coolOffDays=w.coolOffDays??coolDays(w.price)}if(w.status==="ready"&&sv<w.price){w.status="active";delete w.fundedDate}})}
function coolLeft(w){return w.fundedDate?Math.max(0,diffDays(todayISO(),addDays(w.fundedDate,w.coolOffDays||coolDays(w.price)))):0}
function activeWishes(){syncWishes();return state.wishes.filter(w=>w.status==="active"&&wishSaved(w)<w.price)}
function readyWishes(){syncWishes();return state.wishes.filter(w=>w.status==="ready")}
function eligible(w){return daysAgo(w.dateAdded)>=num(w.waitDays||30)}
function thoughtfulness(w){return clamp(Math.min(35,Math.round(daysAgo(w.dateAdded)/Math.max(1,w.waitDays)*35))+num(w.research||0)*7+(w.why?12:0)+(w.betterChecked?12:0)-(w.ownsSimilar?8:0),0,100)}
function applyPaycheckPlan(p){
  if(p.planApplied)return;const snap=p.snapshot||planIncome(p.amount);p.snapshot=snap;p.planApplied=true;
  const goals=state.savingsGoals.filter(g=>goalCurrent(g)<g.target);if(goals.length&&snap.savings>0){const main=goals.find(g=>g.priority==="Main Quest")||goals[0];state.savingsContribs.push({id:uid(),goalId:main.id,paycheckId:p.id,date:p.date,amount:snap.savings})}
  const recs=state.sinkingFunds.map(f=>[f,sinkingRecommendation(f)]).filter(x=>x[1]>0);const total=recs.reduce((a,x)=>a+x[1],0);if(total>0&&snap.sinking>0)recs.forEach(([f,r])=>state.sinkingContribs.push({id:uid(),fundId:f.id,paycheckId:p.id,date:p.date,amount:snap.sinking*(r/total)}));
}

/* ---------- ui helpers ---------- */
const PRIMARY=[["home","🏠","HOME"],["goals","🌱","GOALS"],["wish","📌","WISH"],["play","🎲","PLAY"],["me","💿","ME"]];
const ROUTE_ROOM={home:"home",goals:"goals",wish:"wish",waiting:"wish",envelopes:"wish",ready:"wish",play:"casino",dice:"casino",owned:"owned",closet:"closet",bag:"bag",adventure:"adventure",notebooks:"notes",oops:"oops",money:"money",memory:"memory",settings:"settings",me:"home"};
function primaryFor(r){if(["goals","money"].includes(r))return "goals";if(["wish","waiting","envelopes","ready"].includes(r))return "wish";if(["play","dice","closet","bag","adventure"].includes(r))return "play";if(["me","owned","notebooks","oops","memory","settings"].includes(r))return "me";return "home"}
function renderNav(){const active=primaryFor(route);$("#bottomNav").innerHTML=PRIMARY.map(([id,ic,l])=>`<button class="navbtn ${active===id?"active":""}" data-route="${id}"><i>${ic}</i><span>${l}</span></button>`).join("");$$('[data-route]',$("#bottomNav")).forEach(b=>b.onclick=()=>go(b.dataset.route))}
function go(r){route=r;currentRoll=null;window.scrollTo({top:0,behavior:"instant"});render()}
function setRoom(){const room=ROUTE_ROOM[route]||"home";$("#main").className=`main room-${room}`}
function head(title,add="",mini=""){return `<div class="page-head"><h1 class="page-title">${mini?`<small>${mini}</small>`:""}${title}</h1>${add}</div>`}
function section(title,action=""){return `<div class="section-row"><h2 class="section-label">${title}</h2>${action}</div>`}
function empty(icon,text){return `<div class="empty"><div style="font-size:34px;margin-bottom:6px">${icon}</div>${text}</div>`}
function pctBar(v){return `<div class="progress"><i style="width:${clamp(v,0,100)}%"></i></div>`}
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1700)}
function celebrate(){for(let i=0;i<20;i++){const s=document.createElement("span");s.textContent=["♡","✦","★","💿","🎀"][i%5];s.style.left=Math.random()*100+"%";s.style.animationDelay=Math.random()*.25+"s";$("#confetti").appendChild(s);setTimeout(()=>s.remove(),1800)}}
function modal(title,html,onSave=null,saveLabel="save ♡"){$("#modalTitle").textContent=title;$("#modalBody").innerHTML=html;$("#modalSave").textContent=saveLabel;$("#modalSave").style.display=onSave?"inline-block":"none";$("#modalActions .ghost").textContent=onSave?"cancel":"close";$("#modalSave").onclick=async e=>{e.preventDefault();const ok=await onSave?.();if(ok!==false)$("#modal").close()};$("#modal").showModal();hydrateMedia($("#modal"))}
function confirmDelete(label,fn){if(confirm(`Delete ${label}?`)){fn();saveState();render();toast("deleted ♡")}}
function uploadField(key="",label="photo / gif"){return `<div class="field full"><label>${label}</label><div class="upload-box">${key?mediaImg(key,"upload-preview","preview"):`<div style="font-size:34px">📸</div>`}<input id="fMedia" type="file" accept="image/*,.gif"><div class="tiny">photos, transparent stickers + GIFs stay on this device</div></div></div>`}

/* ---------- media cards ---------- */
function goalCard(g){const cur=goalCurrent(g),p=progressVal(cur,g.target);return `<article class="goal-card"><div class="goal-media">${g.mediaKey?mediaImg(g.mediaKey,"",g.name):`<div class="media-placeholder">${g.type==="Long Term"?"🏡":"🌱"}</div>`}</div><div class="goal-actions"><button class="glass edit-goal" data-id="${g.id}">✎</button><button class="glass del-goal" data-id="${g.id}">×</button></div><div class="goal-copy"><div class="goal-title">${esc(g.name)}</div><div class="moneyline">${money(cur)} / ${money(g.target)}</div>${pctBar(p)}<div class="tiny" style="margin-top:4px">${p}% · ${esc(g.priority||"Goal")}</div></div></article>`}
function pinCard(w){const sv=wishSaved(w),p=progressVal(sv,w.price);return `<article class="pin"><div>${w.mediaKey?mediaImg(w.mediaKey,"",w.name):`<div class="pin-placeholder">${ICONS[w.category]||"♡"}</div>`}</div><div class="pin-actions"><button class="glass edit-wish" data-id="${w.id}">✎</button><button class="glass del-wish" data-id="${w.id}">×</button></div><div class="pin-info"><div class="pin-title">${esc(w.name)}</div><div class="pin-price">${money(w.price)}</div>${w.status==="active"||w.status==="ready"?pctBar(p):""}<div class="tiny-meta"><span class="chip pink">${w.status==="waiting"?(eligible(w)?"READY TO ENVELOPE":`${daysAgo(w.dateAdded)}/${w.waitDays} DAYS`):w.status.toUpperCase()}</span></div></div></article>`}
function ownedCard(o,clickClass=""){return `<article class="owned-card ${clickClass}" data-id="${o.id}">${o.mediaKey?mediaImg(o.mediaKey,"",o.name):`<div class="owned-sticker">${o.category==="Bags"?"👜":"👚"}</div>`}<button class="icon-delete del-owned" data-id="${o.id}">×</button><div class="owned-name">${esc(o.name)}</div><div class="heartline">${"♡".repeat(clamp(num(o.love||5),1,5))}</div></article>`}

/* ---------- home ---------- */
function renderHome(){
  const goals=state.savingsGoals.filter(g=>g.type==="Long Term"||g.priority==="Main Quest");const inspo=state.wishes.filter(w=>["waiting","active","ready"].includes(w.status));const loves=state.owned.slice().sort((a,b)=>num(b.love)-num(a.love));const jar=funJar();
  $("#view").innerHTML=head("money home",`<button class="btn hot" id="homeAdd">＋</button>`,`♡ LOCAL LITTLE WORLD`)+
  section("LONG-TERM GOALS",`<button class="btn mini yellow" id="newGoalHome">+ GOAL</button>`)+
  (goals.length?`<div class="scroll-x">${goals.map(goalCard).join("")}</div>`:empty("🏡","add a future you can see — a house, trip, treatment, anything"))+
  section("WISH INSPO",`<button class="btn mini hot" id="newWishHome">+ PIN</button>`)+
  (inspo.length?`<div class="scroll-x">${inspo.slice(0,12).map(w=>`<div style="width:150px">${pinCard(w)}</div>`).join("")}</div>`:empty("📌","pin something you want to think about, not buy today"))+
  section("I ALREADY LOVE",`<button class="btn mini aqua" id="newOwnedHome">+ LOVE</button>`)+
  (loves.length?`<div class="scroll-x">${loves.slice(0,14).map(ownedCard).join("")}</div>`:empty("💗","build a feed of things you already own and love"))+
  section("FUN MONEY")+`<div class="jar-mini"><div><div class="tiny">AVAILABLE NOW</div><strong>${money(jar)}</strong><div class="tiny">oops buys can honestly subtract from this</div></div><div class="jar-art" style="--fill:${jar>0?65:4}%">♡</div></div>`+
  `<div class="menu-grid" style="margin-top:12px"><button class="menu-card" data-go="notebooks"><i>📝</i>notebooks</button><button class="menu-card" data-go="closet"><i>👗</i>closet</button><button class="menu-card" data-go="adventure"><i>🌳</i>free day</button><button class="menu-card" data-go="oops"><i>🛍️</i>oops</button><button class="menu-card" data-go="dice"><i>🎲</i>roll</button><button class="menu-card" data-go="money"><i>💵</i>money</button></div>`;
  bindCommon();$("#homeAdd").onclick=()=>quickAdd();$("#newGoalHome").onclick=()=>goalModal();$("#newWishHome").onclick=()=>wishModal();$("#newOwnedHome").onclick=()=>ownedModal();$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
}

/* ---------- goals + money ---------- */
function renderGoals(){
  const long=state.savingsGoals.filter(g=>g.type==="Long Term"),other=state.savingsGoals.filter(g=>g.type!=="Long Term");
  $("#view").innerHTML=head("goals",`<button class="btn hot" id="addGoal">+ GOAL</button>`,`MAKE THE FUTURE VISIBLE`)+section("BIG LIFE STUFF")+(long.length?`<div class="scroll-x">${long.map(goalCard).join("")}</div>`:empty("🏠","add a long-term goal + a picture that makes you want it"))+section("OTHER GOALS")+(other.length?`<div class="scroll-x">${other.map(goalCard).join("")}</div>`:empty("🌱","small goals can live here too"))+`<button class="btn aqua" style="width:100%;margin-top:14px" id="moneyPlan">OPEN MONEY PLAN 💵</button>`;
  $("#addGoal").onclick=()=>goalModal();$("#moneyPlan").onclick=()=>go("money");bindCommon();
}
function goalModal(g=null){
  const x=g||{name:"",target:"",baseSaved:0,type:"Long Term",priority:"Main Quest",mediaKey:""};
  modal(g?"edit goal":"new goal",`<div class="form-grid"><div class="field full"><label>goal</label><input id="fName" value="${attr(x.name)}" placeholder="down payment / dream trip / keratin treatment"></div><div class="field"><label>target</label><input id="fTarget" type="number" min="0" step=".01" value="${x.target}"></div><div class="field"><label>saved already</label><input id="fSaved" type="number" min="0" step=".01" value="${x.baseSaved||0}"></div><div class="field"><label>kind</label><select id="fType"><option ${x.type==="Long Term"?"selected":""}>Long Term</option><option ${x.type==="Short Term"?"selected":""}>Short Term</option></select></div><div class="field"><label>priority</label><select id="fPriority"><option ${x.priority==="Main Quest"?"selected":""}>Main Quest</option><option ${x.priority==="Protected"?"selected":""}>Protected</option><option ${x.priority==="Side Quest"?"selected":""}>Side Quest</option></select></div>${uploadField(x.mediaKey,"inspo photo / gif")}</div>`,async()=>{const name=$("#fName").value.trim(),target=num($("#fTarget").value);if(!name||target<=0){toast("name + target first ♡");return false}const mediaKey=await saveUpload($("#fMedia").files[0],x.mediaKey);const data={name,target,baseSaved:num($("#fSaved").value),type:$("#fType").value,priority:$("#fPriority").value,mediaKey};if(g)Object.assign(g,data);else state.savingsGoals.push({id:uid(),...data});saveState();render();toast("goal saved ✦")})
}
function renderMoney(){
  const pay=latestPay();const plan=pay?.snapshot||null;
  $("#view").innerHTML=head("money plan",`<button class="btn hot" id="addPay">+ PAYCHECK</button>`,`REAL NUMBERS ONLY`)+
  `<div class="window"><div class="winbar"><b>money_split.exe</b><span>♡</span></div><div class="window-body"><div class="form-grid"><div class="field"><label>save % of leftover</label><input id="savePct" type="number" min="0" max="100" value="${state.settings.savePct}"></div><div class="field"><label>fun % of leftover</label><input id="funPct" type="number" min="0" max="100" value="${state.settings.funPct}"></div></div><button class="btn lime" id="saveRules" style="margin-top:8px">SAVE RULES</button></div></div>`+
  section("LATEST PAYDAY")+(pay?`<div class="list"><div class="list-item"><div class="list-thumb">💵</div><div class="list-copy"><b>${money(pay.amount)}</b><small>${fmtDate(pay.date)}</small></div><div class="list-actions"><button class="btn mini red del-pay" data-id="${pay.id}">DELETE</button></div></div></div><div class="window" style="margin-top:8px"><div class="window-body"><div class="casino-hud" style="color:inherit"><div class="hud" style="background:#e8ffd9;color:#355"><span>NEEDS</span><b style="color:#234">${money(plan.protected+plan.sinking)}</b></div><div class="hud" style="background:#ffd9ef;color:#624"><span>SAVE</span><b style="color:#523">${money(plan.savings)}</b></div><div class="hud" style="background:#d9ffff;color:#355"><span>FUN</span><b style="color:#234">${money(plan.fun)}</b></div></div></div></div>`:empty("💵","add your actual take-home paycheck — there are no demo numbers"))+
  section("BILLS",`<button class="btn mini aqua" id="addCost">+ BILL</button>`)+(state.costs.length?`<div class="list">${state.costs.map(c=>`<div class="list-item"><div class="list-thumb">🏡</div><div class="list-copy"><b>${esc(c.name)}</b><small>${money(c.amount)} · ${c.frequency}</small></div><div class="list-actions"><button class="btn mini red del-cost" data-id="${c.id}">DELETE</button></div></div>`).join("")}</div>`:empty("🏡","add rent + important expenses"))+
  section("SINKING FUNDS",`<button class="btn mini yellow" id="addSink">+ FUND</button>`)+(state.sinkingFunds.length?`<div class="list">${state.sinkingFunds.map(f=>`<div class="list-item"><div class="list-thumb">🧃</div><div class="list-copy"><b>${esc(f.name)}</b><small>${money(sinkingCurrent(f))} / ${money(f.target)} · ${f.dueDate?money(sinkingRecommendation(f))+" each payday":"no date"}</small></div><div class="list-actions"><button class="btn mini red del-sink" data-id="${f.id}">DELETE</button></div></div>`).join("")}</div>`:empty("🧃","car maintenance, gifts, annual bills — things that sneak up on you"));
  $("#saveRules").onclick=()=>{state.settings.savePct=clamp(num($("#savePct").value),0,100);state.settings.funPct=clamp(num($("#funPct").value),0,100);saveState();toast("rules saved ♡")};$("#addPay").onclick=()=>payModal();$("#addCost").onclick=()=>costModal();$("#addSink").onclick=()=>sinkModal();
  $$(".del-pay").forEach(b=>b.onclick=()=>confirmDelete("paycheck",()=>{state.paychecks=state.paychecks.filter(p=>p.id!==b.dataset.id);state.savingsContribs=state.savingsContribs.filter(c=>c.paycheckId!==b.dataset.id);state.sinkingContribs=state.sinkingContribs.filter(c=>c.paycheckId!==b.dataset.id)}));$$(".del-cost").forEach(b=>b.onclick=()=>confirmDelete("bill",()=>state.costs=state.costs.filter(c=>c.id!==b.dataset.id)));$$(".del-sink").forEach(b=>b.onclick=()=>confirmDelete("fund",()=>{state.sinkingFunds=state.sinkingFunds.filter(f=>f.id!==b.dataset.id);state.sinkingContribs=state.sinkingContribs.filter(c=>c.fundId!==b.dataset.id)}));
}
function payModal(){modal("add paycheck",`<div class="form-grid"><div class="field"><label>date</label><input id="fDate" type="date" value="${todayISO()}"></div><div class="field"><label>take-home amount</label><input id="fAmount" type="number" min="0" step=".01" autofocus></div></div>`,()=>{const amount=num($("#fAmount").value);if(amount<=0){toast("add your real amount ♡");return false}const p={id:uid(),date:$("#fDate").value,amount,snapshot:planIncome(amount),planApplied:false};state.paychecks.push(p);applyPaycheckPlan(p);saveState();render();toast("payday logged 💵")})}
function costModal(){modal("add bill",`<div class="form-grid"><div class="field full"><label>bill / important expense</label><input id="fName"></div><div class="field"><label>amount</label><input id="fAmount" type="number" min="0" step=".01"></div><div class="field"><label>frequency</label><select id="fFreq"><option>monthly</option><option>weekly</option><option>quarterly</option><option>annual</option></select></div></div>`,()=>{const name=$("#fName").value.trim(),amount=num($("#fAmount").value);if(!name||amount<=0)return false;state.costs.push({id:uid(),name,amount,frequency:$("#fFreq").value});saveState();render()})}
function sinkModal(){modal("new sinking fund",`<div class="form-grid"><div class="field full"><label>what for?</label><input id="fName"></div><div class="field"><label>target</label><input id="fTarget" type="number" min="0"></div><div class="field"><label>saved already</label><input id="fSaved" type="number" min="0" value="0"></div><div class="field full"><label>need it by</label><input id="fDate" type="date"></div></div>`,()=>{const name=$("#fName").value.trim(),target=num($("#fTarget").value);if(!name||target<=0)return false;state.sinkingFunds.push({id:uid(),name,target,baseSaved:num($("#fSaved").value),dueDate:$("#fDate").value});saveState();render()})}

/* ---------- wish world ---------- */
function renderWish(){
  const live=state.wishes.filter(w=>["waiting","active","ready"].includes(w.status));
  $("#view").innerHTML=head("wish inspo",`<button class="btn hot" id="addWish">+ PIN</button>`,`LOOK AT IT. WAIT. DECIDE.`)+`<div class="menu-grid" style="margin-bottom:12px"><button class="menu-card" data-go="waiting"><i>💭</i>waiting</button><button class="menu-card" data-go="envelopes"><i>💌</i>envelopes</button><button class="menu-card" data-go="ready"><i>✨</i>ready</button></div>`+(live.length?`<div class="pinboard">${live.map(pinCard).join("")}</div>`:empty("📌","add photos or GIFs so saving feels visual"));
  $("#addWish").onclick=()=>wishModal();$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));bindCommon();
}
function wishModal(w=null){const x=w||{name:"",category:"Things for Me",price:"",dateAdded:todayISO(),waitDays:state.settings.defaultWaitDays,why:"",research:0,betterChecked:false,ownsSimilar:false,status:"waiting",mediaKey:""};modal(w?"edit pin":"new pin",`<div class="form-grid"><div class="field full"><label>what is it?</label><input id="fName" value="${attr(x.name)}"></div><div class="field"><label>price</label><input id="fPrice" type="number" min="0" step=".01" value="${x.price}"></div><div class="field"><label>category</label><select id="fCat">${CATEGORIES.map(c=>`<option ${c===x.category?"selected":""}>${c}</option>`).join("")}</select></div><div class="field"><label>added</label><input id="fDate" type="date" value="${x.dateAdded}"></div><div class="field"><label>wait days</label><input id="fWait" type="number" min="0" value="${x.waitDays}"></div>${uploadField(x.mediaKey)}<details class="field full"><summary>optional smart stuff ✦</summary><div class="form-grid" style="margin-top:8px"><div class="field full"><label>why do i want it?</label><textarea id="fWhy">${esc(x.why||"")}</textarea></div><div class="field"><label>research 0–5</label><input id="fResearch" type="number" min="0" max="5" value="${x.research||0}"></div><div class="field"><label>checked better options?</label><select id="fBetter"><option value="false">not yet</option><option value="true" ${x.betterChecked?"selected":""}>yes</option></select></div><div class="field"><label>own something similar?</label><select id="fSimilar"><option value="false">no</option><option value="true" ${x.ownsSimilar?"selected":""}>yes</option></select></div></div></details></div>`,async()=>{const name=$("#fName").value.trim(),price=num($("#fPrice").value);if(!name||price<=0){toast("name + price first ♡");return false}const mediaKey=await saveUpload($("#fMedia").files[0],x.mediaKey);const data={name,price,category:$("#fCat").value,dateAdded:$("#fDate").value,waitDays:num($("#fWait").value),why:$("#fWhy")?.value||x.why||"",research:num($("#fResearch")?.value||x.research),betterChecked:$("#fBetter")?.value==="true",ownsSimilar:$("#fSimilar")?.value==="true",mediaKey};if(w)Object.assign(w,data);else state.wishes.push({id:uid(),...data,status:"waiting",baseSaved:0});saveState();render();toast("pinned 📌")})}
function renderWaiting(){const xs=state.wishes.filter(w=>w.status==="waiting");$("#view").innerHTML=head("waiting room",`<button class="btn hot" id="addWish">+ PIN</button>`,`30 DAYS = A DECISION, NOT A PURCHASE`)+(xs.length?`<div class="pinboard">${xs.map(pinCard).join("")}</div>`:empty("💭","nothing waiting"));$("#addWish").onclick=()=>wishModal();bindCommon();$$('.pin').forEach(p=>{});xs.filter(eligible).forEach(w=>{const pin=$(`.edit-wish[data-id="${w.id}"]`)?.closest('.pin');if(pin){const b=document.createElement('button');b.className='btn mini lime';b.textContent='MAKE ENVELOPE';b.style.margin='0 7px 7px';b.onclick=()=>{w.status='active';saveState();render();toast('envelope made 💌')};pin.appendChild(b)}})}
function renderEnvelopes(){const xs=activeWishes();$("#view").innerHTML=head("envelopes",`<button class="btn green" id="goRoll">🎲 ROLL</button>`,`ACTIVE = AUTOMATICALLY IN THE GAME`)+(xs.length?`<div class="pinboard">${xs.map(pinCard).join("")}</div>`:empty("💌","promote a waiting wish when it has earned an envelope"));$("#goRoll").onclick=()=>go("dice");bindCommon()}
function renderReady(){const xs=readyWishes();$("#view").innerHTML=head("ready",``,`FULL ≠ MUST BUY`)+(xs.length?`<div class="pinboard">${xs.map(w=>{const left=coolLeft(w);return `<article class="pin"><div>${w.mediaKey?mediaImg(w.mediaKey,"",w.name):`<div class="pin-placeholder">✨</div>`}</div><div class="pin-info"><div class="pin-title">${esc(w.name)}</div><div class="pin-price">${money(w.price)} · ${left?left+" DAY COOL OFF":"DECISION TIME"}</div><div class="tiny-meta">${left?`<span class="chip purple">WAIT</span>`:`<button class="btn mini hot buy-ready" data-id="${w.id}">BUY</button><button class="btn mini aqua better-ready" data-id="${w.id}">BETTER VERSION</button><button class="btn mini lime let-ready" data-id="${w.id}">LET GO</button>`}</div></div></article>`}).join("")}</div>`:empty("✨","nothing fully funded yet"));$$('.buy-ready').forEach(b=>b.onclick=()=>finishWish(b.dataset.id,"bought"));$$('.let-ready').forEach(b=>b.onclick=()=>finishWish(b.dataset.id,"letgo"));$$('.better-ready').forEach(b=>b.onclick=()=>betterVersion(b.dataset.id));}
function finishWish(id,decision){const w=state.wishes.find(x=>x.id===id);if(!w)return;state.memories.push({id:uid(),name:w.name,category:w.category,decision,date:todayISO(),amount:w.price,mediaKey:w.mediaKey,daysWanted:daysAgo(w.dateAdded),joy:0});if(decision==="letgo")state.rolls=state.rolls.filter(r=>r.wishId!==w.id);w.status=decision;saveState();render();celebrate();toast(decision==="bought"?"thoughtful purchase ♡":"changed your mind + fun money returned 🌬")}
function betterVersion(id){const w=state.wishes.find(x=>x.id===id);modal("better version",`<div class="form-grid"><div class="field full"><label>new / better item</label><input id="fName" value="${attr(w.name)}"></div><div class="field"><label>new price</label><input id="fPrice" type="number" min="0" value="${w.price}"></div>${uploadField(w.mediaKey,"new photo / gif")}</div>`,async()=>{const oldPrice=w.price,newPrice=num($("#fPrice").value),mediaKey=await saveUpload($("#fMedia").files[0],w.mediaKey);state.memories.push({id:uid(),name:w.name,category:w.category,decision:"better version",date:todayISO(),amount:Math.max(0,oldPrice-newPrice),mediaKey:w.mediaKey,daysWanted:daysAgo(w.dateAdded),joy:0});w.name=$("#fName").value.trim()||w.name;w.price=newPrice;w.mediaKey=mediaKey;w.status=wishSaved(w)>=newPrice?"ready":"active";saveState();render();toast("upgraded through patience ✦")})}
function bindCommon(){
  $$(".edit-goal").forEach(b=>b.onclick=()=>goalModal(state.savingsGoals.find(g=>g.id===b.dataset.id)));$$(".del-goal").forEach(b=>b.onclick=()=>confirmDelete("goal",()=>{const g=state.savingsGoals.find(x=>x.id===b.dataset.id);Media.del(g?.mediaKey);state.savingsGoals=state.savingsGoals.filter(x=>x.id!==b.dataset.id);state.savingsContribs=state.savingsContribs.filter(c=>c.goalId!==b.dataset.id)}));
  $$(".edit-wish").forEach(b=>b.onclick=()=>wishModal(state.wishes.find(w=>w.id===b.dataset.id)));$$(".del-wish").forEach(b=>b.onclick=()=>confirmDelete("wish",()=>{const w=state.wishes.find(x=>x.id===b.dataset.id);Media.del(w?.mediaKey);state.wishes=state.wishes.filter(x=>x.id!==b.dataset.id);state.rolls=state.rolls.filter(r=>r.wishId!==b.dataset.id)}));
  $$(".del-owned").forEach(b=>b.onclick=e=>{e.stopPropagation();confirmDelete("owned item",()=>{const o=state.owned.find(x=>x.id===b.dataset.id);Media.del(o?.mediaKey);state.owned=state.owned.filter(x=>x.id!==b.dataset.id);selectedOutfit.delete(b.dataset.id);selectedBag.delete(b.dataset.id)})});
  $$(".owned-card").forEach(c=>{if(!c.classList.contains("choose-bag"))c.onclick=e=>{if(e.target.closest(".del-owned"))return;const o=state.owned.find(x=>x.id===c.dataset.id);if(o)ownedModal(o)}});
}

/* ---------- play hub + dice ---------- */
function renderPlay(){$("#view").innerHTML=head("play",``,`SHOP YOUR LIFE / GO DO SOMETHING`)+`<div class="menu-grid"><button class="menu-card" data-go="dice"><i>🎲</i>fun money roll</button><button class="menu-card" data-go="closet"><i>👗</i>dress up</button><button class="menu-card" data-go="bag"><i>👜</i>what's in my bag</button><button class="menu-card" data-go="adventure"><i>🌳</i>free adventure</button></div>`+section("I ALREADY LOVE")+(state.owned.length?`<div class="scroll-x">${state.owned.slice(0,16).map(ownedCard).join("")}</div>`:empty("💗","add things you already own so this tab gives you something else to scroll"));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));bindCommon()}
function chooseRoll(pool){if(!pool.length)return null;let arr=[...pool];if(state.game.mode==="giving")arr=arr.filter(w=>w.category==="Giving & Causes");if(state.game.mode==="treat")arr=arr.filter(w=>["Things for Me","Experiences","Beauty"].includes(w.category));if(!arr.length)arr=pool;if(state.game.mode==="steady"&&state.game.lastWishId&&arr.length>1)arr=arr.filter(w=>w.id!==state.game.lastWishId);if(state.game.mode==="neglected")arr.sort((a,b)=>(a.lastFunded||a.dateAdded).localeCompare(b.lastFunded||b.dateAdded));if(state.game.mode==="neglected")return arr[0];if(state.game.mode==="boost"){const weighted=[];arr.forEach(w=>{const p=progressVal(wishSaved(w),w.price);for(let i=0;i<1+Math.floor(p/25);i++)weighted.push(w)});arr=weighted}return arr[Math.floor(Math.random()*arr.length)]}
function renderDice(){const pool=activeWishes(),jar=funJar();$("#view").innerHTML=head("tiny casino",`<button class="btn yellow" id="modeBtn">${GAME_MODES[state.game.mode]}</button>`,`NO REAL GAMBLING · JUST YOUR ENVELOPES`)+`<div class="casino-hud"><div class="hud">JAR<b>${money(jar)}</b></div><div class="hud">ENVELOPES<b>${pool.length}</b></div><div class="hud">DEPOSIT<b id="depLabel">$1</b></div></div><div class="casino-table"><div class="dice-big">🎲</div>${currentRoll?`<div class="roll-card">${currentRoll.mediaKey?mediaImg(currentRoll.mediaKey,"",currentRoll.name):`<div class="media-placeholder">💌</div>`}<b>${esc(currentRoll.name)}</b><small>${money(wishSaved(currentRoll))} / ${money(currentRoll.price)}</small></div>`:`<div style="font:900 22px 'Trebuchet MS';margin:34px 0 20px">PICK AN ENVELOPE<br>AT RANDOM</div>`}<div class="casino-actions"><select id="deposit" class="btn"><option value="1">$1</option><option value="2">$2</option><option value="5">$5</option><option value="10">$10</option></select><button class="btn hot" id="rollBtn" ${!pool.length||jar<=0?"disabled":""}>ROLL ✦</button>${currentRoll?`<button class="btn lime" id="fundBtn">GIVE IT ♡</button><button class="btn aqua" id="rerouteBtn">REROLL</button>`:""}</div></div>`+section("RECENT")+(state.rolls.length?`<div class="list">${state.rolls.slice(-6).reverse().map(r=>`<div class="list-item"><div class="list-thumb">🎲</div><div class="list-copy"><b>${esc(r.wishName)}</b><small>${fmtDate(r.date)}</small></div><div class="list-actions"><b>${money(r.amount)}</b><button class="btn mini red del-roll" data-id="${r.id}">UNDO</button></div></div>`).join("")}</div>`:empty("🎲","no rolls yet"));$("#rollBtn")?.addEventListener("click",()=>{currentRoll=chooseRoll(pool);if(currentRoll){state.game.lastWishId=currentRoll.id;saveState();renderDice()}});$("#deposit")?.addEventListener("change",e=>$("#depLabel").textContent=money(e.target.value));$("#fundBtn")?.addEventListener("click",()=>{const amt=Math.min(num($("#deposit").value),Math.max(0,funJar()));if(!currentRoll||amt<=0)return;state.rolls.push({id:uid(),wishId:currentRoll.id,wishName:currentRoll.name,date:todayISO(),amount:amt});currentRoll.lastFunded=todayISO();currentRoll=null;syncWishes();saveState();render();celebrate();toast("tiny dollar delivered ♡")});$("#rerouteBtn")?.addEventListener("click",()=>{currentRoll=chooseRoll(pool.filter(w=>w.id!==currentRoll?.id));renderDice()});$("#modeBtn").onclick=()=>modeModal();$$('.del-roll').forEach(b=>b.onclick=()=>confirmDelete("deposit",()=>state.rolls=state.rolls.filter(r=>r.id!==b.dataset.id)));hydrateMedia()}
function modeModal(){modal("game mode",`<div class="menu-grid">${Object.entries(GAME_MODES).map(([k,v])=>`<button type="button" class="menu-card choose-mode" data-mode="${k}"><i>${k==="giving"?"💞":k==="treat"?"🎀":"🎲"}</i>${v}</button>`).join("")}</div>`,null);$$('.choose-mode').forEach(b=>b.onclick=()=>{state.game.mode=b.dataset.mode;saveState();$("#modal").close();render()})}

/* ---------- owned + closet ---------- */
function renderOwned(){$("#view").innerHTML=head("already mine",`<button class="btn aqua" id="addOwned">+ ADD</button>`,`SCROLL THIS INSTEAD OF SHOPPING`)+(state.owned.length?`<div class="closet-grid">${state.owned.map(ownedCard).join("")}</div>`:empty("💗","add things you own and genuinely love"));$("#addOwned").onclick=()=>ownedModal();bindCommon()}
function ownedModal(o=null){const x=o||{name:"",category:"Tops",love:5,note:"",mediaKey:""};modal(o?"edit owned item":"already mine",`<div class="form-grid"><div class="field full"><label>item</label><input id="fName" value="${attr(x.name)}"></div><div class="field"><label>category</label><select id="fCat">${CLOTHES.map(c=>`<option ${c===x.category?"selected":""}>${c}</option>`).join("")}</select></div><div class="field"><label>love 1–5</label><input id="fLove" type="number" min="1" max="5" value="${x.love||5}"></div><div class="field full"><label>why i love it</label><textarea id="fNote">${esc(x.note||"")}</textarea></div>${uploadField(x.mediaKey,"photo / iPhone sticker / transparent PNG")}</div>`,async()=>{const name=$("#fName").value.trim();if(!name)return false;const mediaKey=await saveUpload($("#fMedia").files[0],x.mediaKey);const data={name,category:$("#fCat").value,love:clamp(num($("#fLove").value),1,5),note:$("#fNote").value,mediaKey};if(o)Object.assign(o,data);else state.owned.push({id:uid(),...data});saveState();render();toast("added to your own little world ♡")})}
function renderCloset(){const items=state.owned;$("#view").innerHTML=head("dress-up.exe",`<button class="btn aqua" id="addOwned">+ CLOTHES</button>`,`USE WHAT YOU ALREADY HAVE`)+`<div class="outfit-board" id="outfitBoard">${selectedOutfit.size?[...selectedOutfit].map(id=>{const o=items.find(x=>x.id===id);return o?.mediaKey?mediaImg(o.mediaKey,"",o.name):`<div class="media-placeholder">👚</div>`}).join(""):`<div class="tiny">tap clothes below to build a look</div>`}</div><div style="display:flex;gap:6px;margin:8px 0"><button class="btn hot" id="saveOutfit" ${selectedOutfit.size?"":"disabled"}>SAVE LOOK</button><button class="btn ghost" id="clearOutfit">CLEAR</button></div><div class="closet-grid">${items.map(o=>`<div class="clothing ${selectedOutfit.has(o.id)?"selected":""}" data-cloth="${o.id}">${o.mediaKey?mediaImg(o.mediaKey,"",o.name):`<div class="owned-sticker">👚</div>`}<button class="icon-delete del-owned" data-id="${o.id}">×</button><b>${esc(o.name)}</b></div>`).join("")}</div>`+section("SAVED LOOKS")+(state.outfits.length?`<div class="list">${state.outfits.map(x=>`<div class="list-item"><div class="list-thumb">👗</div><div class="list-copy"><b>${esc(x.name)}</b><small>${x.itemIds.length} pieces</small></div><div class="list-actions"><button class="btn mini red del-outfit" data-id="${x.id}">DELETE</button></div></div>`).join("")}</div>`:empty("👗","save a look you like"));$("#addOwned").onclick=()=>ownedModal();$$('[data-cloth]').forEach(c=>c.onclick=e=>{if(e.target.closest('.del-owned'))return;selectedOutfit.has(c.dataset.cloth)?selectedOutfit.delete(c.dataset.cloth):selectedOutfit.add(c.dataset.cloth);renderCloset()});$("#clearOutfit").onclick=()=>{selectedOutfit.clear();renderCloset()};$("#saveOutfit").onclick=()=>modal("name this look",`<div class="field"><label>look name</label><input id="fName" placeholder="friday night / work / airport"></div>`,()=>{state.outfits.push({id:uid(),name:$("#fName").value.trim()||"look",itemIds:[...selectedOutfit],date:todayISO()});selectedOutfit.clear();saveState();render();toast("look saved ✦")});$$('.del-outfit').forEach(b=>b.onclick=()=>confirmDelete("outfit",()=>state.outfits=state.outfits.filter(x=>x.id!==b.dataset.id)));bindCommon();hydrateMedia()}

/* ---------- what's in my bag ---------- */
function renderBag(){const bags=state.owned.filter(o=>o.category==="Bags"),stuff=state.owned.filter(o=>o.category!=="Bags");const chosenBag=state.bags.find(b=>b.active)||null;$("#view").innerHTML=head("what's in my bag",`<button class="btn aqua" id="addOwned">+ ITEM</button>`,`PACK A BAG WITH THINGS YOU OWN`)+`<div class="bag-stage">${chosenBag?(()=>{const bag=state.owned.find(o=>o.id===chosenBag.bagId);return `${bag?.mediaKey?mediaImg(bag.mediaKey,"bag-image",bag.name):`<div class="media-placeholder">👜</div>`}<h2>${esc(chosenBag.name)}</h2><div class="bag-contents">${chosenBag.itemIds.map(id=>{const o=state.owned.find(x=>x.id===id);return o?.mediaKey?mediaImg(o.mediaKey,"",o.name):`<span class="chip">${esc(o?.name||"")}</span>`}).join("")}</div>`})():`<div style="font-size:70px">👜</div><div class="tiny">choose a bag + pack it</div>`}</div>`+section("BAGS")+(bags.length?`<div class="scroll-x">${bags.map(o=>`<button class="owned-card choose-bag" data-id="${o.id}">${o.mediaKey?mediaImg(o.mediaKey,"",o.name):`<div class="owned-sticker">👜</div>`}<div class="owned-name">${esc(o.name)}</div></button>`).join("")}</div>`:empty("👜","add a bag in Already Mine"))+section("PACK IT")+`<div class="pick-grid">${stuff.map(o=>`<button class="pick-item ${selectedBag.has(o.id)?"on":""}" data-pack="${o.id}">${o.mediaKey?mediaImg(o.mediaKey,"",o.name):`<div style="font-size:24px">✨</div>`}<span>${esc(o.name)}</span></button>`).join("")}</div><button class="btn hot" style="width:100%;margin-top:9px" id="saveBag" ${!bags.length?"disabled":""}>SAVE THIS BAG</button>`+section("SAVED BAGS")+(state.bags.length?`<div class="list">${state.bags.map(b=>`<div class="list-item"><div class="list-thumb">👜</div><div class="list-copy"><b>${esc(b.name)}</b><small>${b.itemIds.length} things</small></div><div class="list-actions"><button class="btn mini aqua use-bag" data-id="${b.id}">OPEN</button><button class="btn mini red del-bag" data-id="${b.id}">DELETE</button></div></div>`).join("")}</div>`:empty("👜","save a bag setup"));$("#addOwned").onclick=()=>ownedModal();$$('.choose-bag').forEach(b=>b.onclick=()=>{state.bags.forEach(x=>x.active=false);state.bags.push({id:uid(),name:state.owned.find(o=>o.id===b.dataset.id)?.name||"bag",bagId:b.dataset.id,itemIds:[],active:true});saveState();renderBag()});$$('[data-pack]').forEach(b=>b.onclick=()=>{selectedBag.has(b.dataset.pack)?selectedBag.delete(b.dataset.pack):selectedBag.add(b.dataset.pack);renderBag()});$("#saveBag").onclick=()=>{let b=state.bags.find(x=>x.active);if(!b){const bag=bags[0];b={id:uid(),name:bag.name,bagId:bag.id,itemIds:[],active:true};state.bags.push(b)}b.itemIds=[...selectedBag];selectedBag.clear();saveState();render();toast("bag packed 👜")};$$('.use-bag').forEach(b=>b.onclick=()=>{state.bags.forEach(x=>x.active=x.id===b.dataset.id);saveState();renderBag()});$$('.del-bag').forEach(b=>b.onclick=()=>confirmDelete("saved bag",()=>state.bags=state.bags.filter(x=>x.id!==b.dataset.id)));hydrateMedia()}

/* ---------- free adventure ---------- */
function randomAdventure(){const acts=[...BUILTIN_ACTIVITIES,...state.customActivities.map(x=>x.name)];return {activity:acts[Math.floor(Math.random()*acts.length)],who:WHO[Math.floor(Math.random()*WHO.length)],where:WHERE[Math.floor(Math.random()*WHERE.length)],when:WHEN[Math.floor(Math.random()*WHEN.length)]}}
function renderAdventure(){$("#view").innerHTML=head("free adventure",`<button class="btn aqua" id="addActivity">+ IDEA</button>`,`SPEND TIME, NOT MONEY`)+`<div class="adventure-machine"><div style="font-size:48px">🌳 💿 ☀️</div><div class="adventure-result">${adventureRoll?`<div><h2>${esc(adventureRoll.activity)}</h2><div class="adventure-meta"><span class="chip pink">${esc(adventureRoll.who)}</span><span class="chip aqua">${esc(adventureRoll.where)}</span><span class="chip green">${esc(adventureRoll.when)}</span></div></div>`:`<div><h2>WHAT SHOULD I DO?</h2><div class="tiny">random free fun + hobby ideas</div></div>`}</div><button class="btn hot" id="adventureBtn">SURPRISE ME ✦</button>${adventureRoll?`<button class="btn lime" id="saveAdventure">I DID THIS ♡</button>`:""}</div>`+section("RECENT FREE FUN")+(state.adventures.length?`<div class="pinboard">${state.adventures.slice().reverse().map(a=>`<article class="pin"><div>${a.mediaKey?mediaImg(a.mediaKey,"",a.activity):`<div class="pin-placeholder">🌳</div>`}</div><div class="pin-actions"><button class="glass del-adv" data-id="${a.id}">×</button></div><div class="pin-info"><div class="pin-title">${esc(a.activity)}</div><div class="tiny">${fmtDate(a.date)} · ${esc(a.who||"")}</div></div></article>`).join("")}</div>`:empty("☀️","do something free, then keep the memory here"))+section("MY RANDOMIZER IDEAS")+(state.customActivities.length?`<div class="list">${state.customActivities.map(a=>`<div class="list-item"><div class="list-thumb">✦</div><div class="list-copy"><b>${esc(a.name)}</b><small>custom free idea</small></div><div class="list-actions"><button class="btn mini red del-activity" data-id="${a.id}">DELETE</button></div></div>`).join("")}</div>`:empty("✦","add your own free ideas to the randomizer"));$("#adventureBtn").onclick=()=>{adventureRoll=randomAdventure();renderAdventure()};$("#addActivity").onclick=()=>activityModal();$("#saveAdventure")?.addEventListener("click",()=>adventureDoneModal(adventureRoll));$$('.del-adv').forEach(b=>b.onclick=()=>confirmDelete("adventure",()=>{const a=state.adventures.find(x=>x.id===b.dataset.id);Media.del(a?.mediaKey);state.adventures=state.adventures.filter(x=>x.id!==b.dataset.id)}));$$('.del-activity').forEach(b=>b.onclick=()=>confirmDelete("free idea",()=>state.customActivities=state.customActivities.filter(x=>x.id!==b.dataset.id)));hydrateMedia()}
function activityModal(){modal("add free idea",`<div class="field"><label>free thing to do</label><input id="fName" placeholder="make friendship bracelets with supplies I own"></div>`,()=>{const name=$("#fName").value.trim();if(!name)return false;state.customActivities.push({id:uid(),name});saveState();render();toast("added to the randomizer ✦")})}
function adventureDoneModal(a){modal("free memory",`<div class="form-grid"><div class="field full"><label>what happened?</label><input id="fActivity" value="${attr(a.activity)}"></div><div class="field"><label>who</label><input id="fWho" value="${attr(a.who)}"></div><div class="field"><label>where</label><input id="fWhere" value="${attr(a.where)}"></div>${uploadField("","little photo / gif")}</div>`,async()=>{const mediaKey=await saveUpload($("#fMedia").files[0]);state.adventures.push({id:uid(),activity:$("#fActivity").value,who:$("#fWho").value,where:$("#fWhere").value,when:a.when,date:todayISO(),mediaKey});adventureRoll=null;saveState();render();celebrate();toast("free fun saved ☀️")})}

/* ---------- notebooks ---------- */
function renderNotebooks(){if(!state.notebooks.length)state.notebooks.push({id:uid(),title:"new notebook",body:"",color:"pink"});if(!state.notebooks.some(n=>n.id===activeNotebook))activeNotebook=state.notebooks[0].id;const n=state.notebooks.find(x=>x.id===activeNotebook);$("#view").innerHTML=head("notebooks",`<button class="btn yellow" id="newBook">+ BOOK</button>`,`WRITE YOUR OWN RULES`)+`<div class="notebook-tabs">${state.notebooks.map(x=>`<button class="book-tab ${x.id===activeNotebook?"active":""}" data-book="${x.id}">${esc(x.title)}</button>`).join("")}</div><div class="notebook"><input class="notebook-title" id="bookTitle" value="${attr(n.title)}"><textarea id="bookBody" placeholder="no delivery this week...\nthings I want more than random shopping...\nremind myself why I am saving...">${esc(n.body||"")}</textarea><div class="list-actions"><button class="btn mini hot" id="saveBook">SAVE</button><button class="btn mini red" id="delBook">DELETE NOTEBOOK</button></div></div>`;$$('[data-book]').forEach(b=>b.onclick=()=>{activeNotebook=b.dataset.book;renderNotebooks()});$("#newBook").onclick=()=>{const x={id:uid(),title:"new notebook",body:"",color:"pink"};state.notebooks.push(x);activeNotebook=x.id;saveState();renderNotebooks()};$("#saveBook").onclick=()=>{n.title=$("#bookTitle").value.trim()||"notebook";n.body=$("#bookBody").value;saveState();toast("notebook saved 📝")};$("#delBook").onclick=()=>confirmDelete("notebook",()=>{state.notebooks=state.notebooks.filter(x=>x.id!==n.id);activeNotebook=state.notebooks[0]?.id||null})}

/* ---------- oops ---------- */
function renderOops(){const total=impulseOut();$("#view").innerHTML=head("oops!",`<button class="btn red" id="addOops">+ OOPS</button>`,`HONEST, NOT SHAMEY`)+`<div class="jar-mini"><div><div class="tiny">DEDUCTED FROM FUN</div><strong>${money(total)}</strong></div><div class="jar-art" style="--fill:${total?80:5}%">🛍️</div></div>`+section("LATELY")+(state.impulses.length?state.impulses.slice().reverse().map(x=>`<article class="oops-card ${x.returned?"returned":""}">${x.mediaKey?mediaImg(x.mediaKey,"",x.name):`<div class="media-placeholder">🛍️</div>`}<div><b>${esc(x.name)}</b><div class="oops-money">${money(x.amount)}</div><div class="tiny">${x.deductFun?"deducts fun money":"logged only"} · ${fmtDate(x.date)}</div><p class="tiny">${esc(x.note||"")}</p><div class="list-actions"><button class="btn mini aqua return-oops" data-id="${x.id}">${x.returned?"UNRETURN":"RETURNED"}</button><button class="btn mini red del-oops" data-id="${x.id}">DELETE</button></div></div></article>`).join(""):empty("🛍️","log an impulse buy if you want the fun-money number to be brutally honest"));$("#addOops").onclick=()=>oopsModal();$$('.return-oops').forEach(b=>b.onclick=()=>{const x=state.impulses.find(o=>o.id===b.dataset.id);x.returned=!x.returned;saveState();render()});$$('.del-oops').forEach(b=>b.onclick=()=>confirmDelete("oops buy",()=>{const x=state.impulses.find(o=>o.id===b.dataset.id);Media.del(x?.mediaKey);state.impulses=state.impulses.filter(o=>o.id!==b.dataset.id)}));hydrateMedia()}
function oopsModal(){modal("oops, i bought this",`<div class="form-grid"><div class="field full"><label>what was it?</label><input id="fName"></div><div class="field"><label>amount</label><input id="fAmount" type="number" min="0" step=".01"></div><div class="field"><label>date</label><input id="fDate" type="date" value="${todayISO()}"></div><div class="field full"><label>honest note</label><textarea id="fNote" placeholder="why did I buy it / how do I feel about it now?"></textarea></div><div class="field full"><label><input id="fDeduct" type="checkbox" checked> deduct this from my Fun Money Jar</label></div>${uploadField()}</div>`,async()=>{const name=$("#fName").value.trim(),amount=num($("#fAmount").value);if(!name||amount<=0)return false;const mediaKey=await saveUpload($("#fMedia").files[0]);state.impulses.push({id:uid(),name,amount,date:$("#fDate").value,note:$("#fNote").value,deductFun:$("#fDeduct").checked,returned:false,mediaKey});saveState();render();toast("logged honestly ♡")})}

/* ---------- memory ---------- */
function renderMemory(){const letgo=state.memories.filter(m=>m.decision==="letgo").reduce((a,m)=>a+num(m.amount),0);$("#view").innerHTML=head("memory box",``,`THINGS YOU BOUGHT / DIDN'T BUY`)+`<div class="casino-hud"><div class="hud" style="background:#fff;color:#633">MEMORIES<b style="color:#432">${state.memories.length}</b></div><div class="hud" style="background:#fff;color:#633">LET GO VALUE<b style="color:#432">${money(letgo)}</b></div><div class="hud" style="background:#fff;color:#633">FREE DAYS<b style="color:#432">${state.adventures.length}</b></div></div>`+(state.memories.length?`<div class="pinboard">${state.memories.slice().reverse().map(m=>`<article class="pin"><div>${m.mediaKey?mediaImg(m.mediaKey,"",m.name):`<div class="pin-placeholder">🌷</div>`}</div><div class="pin-actions"><button class="glass del-memory" data-id="${m.id}">×</button></div><div class="pin-info"><div class="pin-title">${esc(m.name)}</div><div class="tiny">${esc(m.decision)} · ${fmtDate(m.date)}</div></div></article>`).join("")}</div>`:empty("🌷","the endings will live here"));$$('.del-memory').forEach(b=>b.onclick=()=>confirmDelete("memory",()=>state.memories=state.memories.filter(m=>m.id!==b.dataset.id)));hydrateMedia()}

/* ---------- me + settings ---------- */
function renderMe(){$("#view").innerHTML=head("my little world",``,`THINGS TO DO INSTEAD OF BUY`)+`<div class="menu-grid"><button class="menu-card" data-go="owned"><i>💗</i>already mine</button><button class="menu-card" data-go="notebooks"><i>📝</i>notebooks</button><button class="menu-card" data-go="oops"><i>🛍️</i>oops!</button><button class="menu-card" data-go="memory"><i>🌷</i>memory</button><button class="menu-card" data-go="money"><i>💵</i>money</button><button class="menu-card" data-go="settings"><i>🖼️</i>wallpapers</button></div>`+section("ALREADY MINE")+(state.owned.length?`<div class="scroll-x">${state.owned.slice(0,14).map(ownedCard).join("")}</div>`:empty("💗","fill this with things you already love"));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));bindCommon()}
function renderSettings(){const rooms=["home","goals","wish","casino","notes","closet","bag","adventure","oops","owned","money","memory"];$("#view").innerHTML=head("wallpaper studio",``,`MIXED MEDIA MODE`)+`<div class="window"><div class="winbar"><b>room_wallpaper.exe</b><span>🖼️</span></div><div class="window-body"><div class="field"><label>room</label><select id="bgRoom">${rooms.map(r=>`<option value="${r}">${r}</option>`).join("")}</select></div><div class="field" style="margin-top:8px"><label>background photo / gif</label><input id="bgFile" type="file" accept="image/*,.gif"></div><div style="display:flex;gap:6px;margin-top:8px"><button class="btn hot" id="saveBg">SET WALLPAPER</button><button class="btn red" id="clearBg">CLEAR</button></div><p class="tiny">You can make the notebooks paper-y, casino green, closet white, and still layer your own photo or GIF on top. Media stays local.</p></div></div>`+section("APP")+`<div class="window"><div class="window-body"><label class="chip pink"><input id="sparkleToggle" type="checkbox" ${state.settings.sparkle?"checked":""}> sparkles</label><button class="btn aqua" id="exportBtn" style="margin:8px 5px 0 0">EXPORT BACKUP</button><label class="btn yellow" style="display:inline-block;margin-top:8px">IMPORT<input id="importFile" type="file" accept=".json" hidden></label></div></div>`;$("#sparkleToggle").onchange=e=>{state.settings.sparkle=e.target.checked;saveState();render()};$("#saveBg").onclick=async()=>{const room=$("#bgRoom").value,file=$("#bgFile").files[0];if(!file)return toast("choose a photo or GIF");const old=state.settings.roomBackgrounds[room]||"";state.settings.roomBackgrounds[room]=await saveUpload(file,old);saveState();toast("wallpaper set ✦");render()};$("#clearBg").onclick=()=>{const room=$("#bgRoom").value,key=state.settings.roomBackgrounds[room];Media.del(key);delete state.settings.roomBackgrounds[room];saveState();render();toast("wallpaper cleared")};$("#exportBtn").onclick=exportBackup;$("#importFile").onchange=e=>importBackup(e.target.files[0])}

/* ---------- quick add / backup ---------- */
function quickAdd(){modal("quick add",`<div class="menu-grid"><button type="button" class="menu-card q" data-q="goal"><i>🌱</i>goal</button><button type="button" class="menu-card q" data-q="wish"><i>📌</i>wish</button><button type="button" class="menu-card q" data-q="owned"><i>💗</i>already mine</button><button type="button" class="menu-card q" data-q="oops"><i>🛍️</i>oops</button><button type="button" class="menu-card q" data-q="pay"><i>💵</i>paycheck</button><button type="button" class="menu-card q" data-q="book"><i>📝</i>notebook</button></div>`,null);$$('.q').forEach(b=>b.onclick=()=>{$("#modal").close();({goal:goalModal,wish:wishModal,owned:ownedModal,oops:oopsModal,pay:payModal,book:()=>go("notebooks")}[b.dataset.q])()})}
async function blobToDataURL(blob){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
function dataURLToBlob(data){const [meta,b64]=data.split(',');const mime=meta.match(/data:(.*?);/)?.[1]||'application/octet-stream';const bytes=atob(b64);const arr=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)arr[i]=bytes.charCodeAt(i);return new Blob([arr],{type:mime})}
async function exportBackup(){toast("building scrapbook backup...");const media={};for(const k of await Media.keys()){const b=await Media.get(k);if(b)media[k]=await blobToDataURL(b)}const payload={app:"My Little Money Home",version:5,exported:new Date().toISOString(),state,media};const blob=new Blob([JSON.stringify(payload)],{type:"application/json"});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`moneyhome-backup-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("backup saved 💾")}
async function importBackup(file){if(!file)return;try{const p=JSON.parse(await file.text());state=normalize(p.state||p);if(p.media)for(const [k,v] of Object.entries(p.media))await Media.put(dataURLToBlob(v),k);saveState();render();toast("little world restored ♡")}catch(e){console.error(e);toast("couldn't read that backup")}}

/* ---------- render ---------- */
function render(){syncWishes();renderNav();setRoom();document.body.classList.toggle("sparkle-mode",!!state.settings.sparkle);const routes={home:renderHome,goals:renderGoals,money:renderMoney,wish:renderWish,waiting:renderWaiting,envelopes:renderEnvelopes,ready:renderReady,play:renderPlay,dice:renderDice,owned:renderOwned,closet:renderCloset,bag:renderBag,adventure:renderAdventure,notebooks:renderNotebooks,oops:renderOops,memory:renderMemory,me:renderMe,settings:renderSettings};(routes[route]||renderHome)();saveState();hydrateMedia()}
$("#sparkleBtn").onclick=()=>{state.settings.sparkle=!state.settings.sparkle;saveState();render()};$("#moreBtn").onclick=()=>go("me");$$('[data-route]',$(".app-head")).forEach(b=>b.onclick=()=>go(b.dataset.route));
setTimeout(()=>$("#boot").classList.add("hide"),900);
if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(console.warn);
render();
